// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signature.proto

package com.obomprogramador.grpc;

public interface SignVerifyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signverify.SignVerifyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool verificationResult = 1;</code>
   */
  boolean getVerificationResult();
}
