// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signature.proto

package com.obomprogramador.grpc;

public final class SignVerifyServer {
  private SignVerifyServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signverify_SignVerifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signverify_SignVerifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signverify_SignVerifyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signverify_SignVerifyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017signature.proto\022\nsignverify\"7\n\021SignVer" +
      "ifyRequest\022\014\n\004text\030\001 \001(\t\022\024\n\014hexSignature" +
      "\030\002 \001(\t\"0\n\022SignVerifyResponse\022\032\n\022verifica" +
      "tionResult\030\001 \001(\0102`\n\nSignVerify\022R\n\017Verify" +
      "Signature\022\035.signverify.SignVerifyRequest" +
      "\032\036.signverify.SignVerifyResponse\"\000B4\n\030co" +
      "m.obomprogramador.grpcB\020SignVerifyServer" +
      "P\001\242\002\003SVCb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_signverify_SignVerifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signverify_SignVerifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signverify_SignVerifyRequest_descriptor,
        new java.lang.String[] { "Text", "HexSignature", });
    internal_static_signverify_SignVerifyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_signverify_SignVerifyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signverify_SignVerifyResponse_descriptor,
        new java.lang.String[] { "VerificationResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)

  private static class SignVerifyService extends SignVerifyGrpc.SignVerifyImplBase {
    
  }
}
