// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signature.proto

package com.obomprogramador.grpc;

public interface SignVerifyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signverify.SignVerifyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string hexSignature = 2;</code>
   */
  java.lang.String getHexSignature();
  /**
   * <code>string hexSignature = 2;</code>
   */
  com.google.protobuf.ByteString
      getHexSignatureBytes();
}
