# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signature.proto',
  package='signverify',
  syntax='proto3',
  serialized_options=_b('\n\030com.obomprogramador.grpcB\020SignVerifyServerP\001\242\002\003SVC'),
  serialized_pb=_b('\n\x0fsignature.proto\x12\nsignverify\"7\n\x11SignVerifyRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0chexSignature\x18\x02 \x01(\t\"0\n\x12SignVerifyResponse\x12\x1a\n\x12verificationResult\x18\x01 \x01(\x08\x32`\n\nSignVerify\x12R\n\x0fVerifySignature\x12\x1d.signverify.SignVerifyRequest\x1a\x1e.signverify.SignVerifyResponse\"\x00\x42\x34\n\x18\x63om.obomprogramador.grpcB\x10SignVerifyServerP\x01\xa2\x02\x03SVCb\x06proto3')
)




_SIGNVERIFYREQUEST = _descriptor.Descriptor(
  name='SignVerifyRequest',
  full_name='signverify.SignVerifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='signverify.SignVerifyRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hexSignature', full_name='signverify.SignVerifyRequest.hexSignature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=86,
)


_SIGNVERIFYRESPONSE = _descriptor.Descriptor(
  name='SignVerifyResponse',
  full_name='signverify.SignVerifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verificationResult', full_name='signverify.SignVerifyResponse.verificationResult', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['SignVerifyRequest'] = _SIGNVERIFYREQUEST
DESCRIPTOR.message_types_by_name['SignVerifyResponse'] = _SIGNVERIFYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignVerifyRequest = _reflection.GeneratedProtocolMessageType('SignVerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNVERIFYREQUEST,
  '__module__' : 'signature_pb2'
  # @@protoc_insertion_point(class_scope:signverify.SignVerifyRequest)
  })
_sym_db.RegisterMessage(SignVerifyRequest)

SignVerifyResponse = _reflection.GeneratedProtocolMessageType('SignVerifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNVERIFYRESPONSE,
  '__module__' : 'signature_pb2'
  # @@protoc_insertion_point(class_scope:signverify.SignVerifyResponse)
  })
_sym_db.RegisterMessage(SignVerifyResponse)


DESCRIPTOR._options = None

_SIGNVERIFY = _descriptor.ServiceDescriptor(
  name='SignVerify',
  full_name='signverify.SignVerify',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='VerifySignature',
    full_name='signverify.SignVerify.VerifySignature',
    index=0,
    containing_service=None,
    input_type=_SIGNVERIFYREQUEST,
    output_type=_SIGNVERIFYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNVERIFY)

DESCRIPTOR.services_by_name['SignVerify'] = _SIGNVERIFY

# @@protoc_insertion_point(module_scope)
